authors:
  Rexyz:
    name: Xu Hao    # Author name
    description: Mediocre but diligent # Author description
    avatar: https://www.helloimg.com/i/2025/01/31/679c5074d443c.jpg        # Author avatar